name: Deploy to Server
run-name: Server Deployment 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Add server to known_hosts
      run: |
        echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: List files for debug
      run: |
        ls -la /home/runner/work/Billions-Charts/Billions-Charts/
      
    # - name: Deploy app.py 
    #   uses: easingthemes/ssh-deploy@v2.1.4
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
    #     REMOTE_HOST: ${{ secrets.IP_ADRESS }}
    #     REMOTE_USER: ${{ secrets.USERNAME }}
    #     REMOTE_PORT: 5022
    #     SOURCE: "app.py"
    #     TARGET: "/home/${{ secrets.USERNAME }}/billions-charts/"
      
    - name: Deploy backend/
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.IP_ADRESS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        REMOTE_PORT: 5022
        SOURCE: "backend/"
        TARGET: "/home/${{ secrets.USERNAME }}/billions-charts/backend/"
      
    # - name: Deploy public/
    #   uses: easingthemes/ssh-deploy@v2.1.4
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
    #     REMOTE_HOST: ${{ secrets.IP_ADRESS }}
    #     REMOTE_USER: ${{ secrets.USERNAME }}
    #     REMOTE_PORT: 5022
    #     SOURCE: "public/"
    #     TARGET: "/home/${{ secrets.USERNAME }}/billions-charts/public/"
    #     ARGS: "--exclude='data/'"