name: Deploy to Server
run-name: Server Deployment 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Add server to known_hosts
      run: |
        echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: Deploy files to server
      run: |
        rsync -e "ssh -p 5022" -avz --exclude='.env' --exclude='.git/' ./ dybedywe@185.221.182.209:/home/dybedywe/billions-test/
